export const CNutrientUnits = {
  calories: { name: 'Calories', unit: 'kcal' },
  fat: { name: 'Fat', unit: 'g' },
  transFat: { name: 'Trans Fat', unit: 'g' },
  saturatedFat: { name: 'Saturated Fat', unit: 'g' },
  monoUnsaturatedFat: { name: 'Mono Unsaturated Fat', unit: 'g' },
  polyUnsaturatedFat: { name: 'Poly Unsaturated Fat', unit: 'g' },
  protein: { name: 'Protein', unit: 'g' },
  cholesterol: { name: 'Cholesterol', unit: 'mg' },
  carbohydrates: { name: 'Carbohydrates', unit: 'g' },
  netCarbohydrates: { name: 'Net Carbohydrates', unit: 'g' },
  alcohol: { name: 'Alcohol', unit: 'g' },
  fiber: { name: 'Fiber', unit: 'g' },
  sugar: { name: 'Sugar', unit: 'g' },
  sodium: { name: 'Sodium', unit: 'mg' },
  caffeine: { name: 'Caffeine', unit: 'mg' },
  manganese: { name: 'Manganese', unit: 'mg' },
  potassium: { name: 'Potassium', unit: 'mg' },
  magnesium: { name: 'Magnesium', unit: 'mg' },
  calcium: { name: 'Calcium', unit: 'mg' },
  copper: { name: 'Copper', unit: 'mg' },
  zinc: { name: 'Zinc', unit: 'mg' },
  phosphorus: { name: 'Phosphorus', unit: 'mg' },
  fluoride: { name: 'Fluoride', unit: 'mg' },
  choline: { name: 'Choline', unit: 'mg' },
  iron: { name: 'Iron', unit: 'mg' },
  vitaminA: { name: 'Vitamin A', unit: 'IU' },
  vitaminB1: { name: 'Vitamin B1', unit: 'mg' },
  vitaminB2: { name: 'Vitamin B2', unit: 'mg' },
  vitaminB3: { name: 'Vitamin B3', unit: 'mg' },
  vitaminB5: { name: 'Vitamin B5', unit: 'mg' },
  vitaminB6: { name: 'Vitamin B6', unit: 'mg' },
  vitaminB12: { name: 'Vitamin B12', unit: 'Âµg' },
  vitaminC: { name: 'Vitamin C', unit: 'mg' },
  vitaminD: { name: 'Vitamin D', unit: 'Âµg' },
  vitaminE: { name: 'Vitamin E', unit: 'mg' },
  vitaminK: { name: 'Vitamin K', unit: 'Âµg' },
  folate: { name: 'Folate', unit: 'Âµg' },
  folicAcid: { name: 'Folic Acid', unit: 'Âµg' },
  iodine: { name: 'Iodine', unit: 'Âµg' },
  selenium: { name: 'Selenium', unit: 'Âµg' }
};
