/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ApiLinks {
  /**
   * direct api link to the ingredient - get
   */
  self?: string;
  /**
   * direct api link to the recipe Schema or to recipe type or to parent of the ingredient - ie flour
   */
  parent?: string;
}
