/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BookingRecipe } from './bookingRecipe';
import { BookingTeachersName } from './bookingTeachersName';

export interface Booking {
  readonly id?: string;
  recipe?: BookingRecipe;
  /**
   * time and date recipe is booked for
   */
  timeBooked?: Date;
  /**
   * Name of the college to assist in search
   */
  schoolName?: string;
  /**
   * completing this field disables timeBooked and autopopulates it depending on weekly timetable
   */
  periodBooked?: string;
  teachersName?: BookingTeachersName;
  /**
   * Further clues as to where the recipe is being booked
   */
  roomName?: string;
  /**
   * Future addition of classes linked to teachers maybe?
   */
  studentGroupName?: string;
  /**
   * Notes for the Food technician
   */
  prepNotes?: string;
}
