/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface History {
  readonly id?: string;
  eventDate?: Date;
  /**
   * event that occurred edit, booked, favourited, created
   */
  event?: string;
  /**
   * used in an update
   */
  changeKey?: string;
  /**
   * used in an update
   */
  changeFrom?: string;
  /**
   * used in an update
   */
  changeTo?: string;
  /**
   * polite name of user
   */
  userName?: string;
}
