/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Picture {
  id?: number;
  /**
   * if using GridFS - optional field
   */
  fileId?: string;
  /**
   * if none provided - use the recipe name - to populate the alt text of an img
   */
  title?: string;
  /**
   * pure URL location or file_id string if using GridFS
   */
  fileLink: string;
  /**
   * top (banner), left (float left) or right (float right)
   */
  positionPic?: string;
}
