/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RatingReviews {
  id?: number;
  recipeId: number;
  // number 0-10 - which presents 3.5/5 stars
  rating: number;

  createdAt: number | Date;
  // Review - YUM
  title: string;
  // big text field describing improvements to make etc
  review?: string;
  // mongoose objectId - so can use populate to expand the information
  userID?: number;
}
