/**
 * Provisioners CookBook Api
 * This is the API for the Provisioner's CookBook Project
 *
 * OpenAPI spec version: 1.0.0-oas3
 * Contact: ianoxwell@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RecipeCreatedByUser {
  /**
   * used to search through with a name change; also search for user profile on click then navigateTo
   */
  userID?: string;
  /**
   * polite name reference
   */
  userName?: string;
  /**
   * api link to the user profile
   */
  link?: string;
}
